// BEGIN MODULE: workers/ui/defaults
function resetTabToAllgemeinOnOpen() {
  setAttrsSilent({ sr6_daten_tab: "allgemein" });
}

function getEditModeResetPayload() {
  return {
    sr6_allgemein_attribute_edit_mode: "0",
    sr6_allgemein_initiative_edit_mode: "0",
    sr6_allgemein_fertigkeiten_view: "fertigkeiten",
    sr6_fertigkeiten_edit_mode: "0",
    sr6_allgemein_kampf_edit_mode: "0",
    sr6_allgemein_verteidigung_edit_mode: "0",
    sr6_allgemein_schadenswiderstand_edit_mode: "0",
    sr6_magic_zauber_edit_mode: "0",
    sr6_magic_adeptenkraefte_edit_mode: "0",
    sr6_magic_foki_edit_mode: "0",
    sr6_magic_metamagie_edit_mode: "0",
    sr6_magic_rituale_edit_mode: "0",
    sr6_magic_geister_edit_mode: "0",
    sr6_matrix_programme_edit_mode: "0",
    sr6_matrix_geraete_edit_mode: "0",
    sr6_matrix_handlungen_edit_mode: "0",
    sr6_rigging_fahrzeuge_edit_mode: "0",
    sr6_rigging_programme_edit_mode: "0",
    sr6_rigging_zubehoer_edit_mode: "0",
    sr6_rigging_agenten_edit_mode: "0",
    sr6_rigging_manoever_edit_mode: "0",
    sr6_ausruestung_edit_mode: "0",
    sr6_cyberware_edit_mode: "0",
    sr6_bioware_edit_mode: "0",
    sr6_sin_edit_mode: "0",
    sr6_lebensstil_edit_mode: "0",
    sr6_setting_popup_mods: "eigen",
    sr6_roll_popup_open: "0",
    sr6_roll_popup_definition: "",
    sr6_roll_popup_slot_1_visible: "0",
    sr6_roll_popup_slot_2_visible: "0",
    sr6_roll_popup_slot_3_visible: "0",
    sr6_roll_popup_slot_1_is_number: "0",
    sr6_roll_popup_slot_2_is_number: "0",
    sr6_roll_popup_slot_3_is_number: "0",
    sr6_roll_popup_slot_1_is_select: "0",
    sr6_roll_popup_slot_2_is_select: "0",
    sr6_roll_popup_slot_3_is_select: "0",
    sr6_roll_popup_slot_1_label: "",
    sr6_roll_popup_slot_2_label: "",
    sr6_roll_popup_slot_3_label: "",
    sr6_roll_popup_slot_1_option_visibility: "0",
    sr6_roll_popup_slot_2_option_visibility: "0",
    sr6_roll_popup_slot_3_option_visibility: "0",
    sr6_roll_popup_slot_1_option_movement: "0",
    sr6_roll_popup_slot_2_option_movement: "0",
    sr6_roll_popup_slot_3_option_movement: "0",
    sr6_roll_popup_slot_1_option_spell_range: "0",
    sr6_roll_popup_slot_2_option_spell_range: "0",
    sr6_roll_popup_slot_3_option_spell_range: "0",
    sr6_roll_popup_slot_1_option_matrix_access: "0",
    sr6_roll_popup_slot_2_option_matrix_access: "0",
    sr6_roll_popup_slot_3_option_matrix_access: "0",
    sr6_roll_popup_value_1_number: "0",
    sr6_roll_popup_value_2_number: "0",
    sr6_roll_popup_value_3_number: "0",
    sr6_roll_popup_value_1_select_visibility: "",
    sr6_roll_popup_value_2_select_visibility: "",
    sr6_roll_popup_value_3_select_visibility: "",
    sr6_roll_popup_value_1_select_movement: "",
    sr6_roll_popup_value_2_select_movement: "",
    sr6_roll_popup_value_3_select_movement: "",
    sr6_roll_popup_value_1_select_spell_range: "",
    sr6_roll_popup_value_2_select_spell_range: "",
    sr6_roll_popup_value_3_select_spell_range: "",
    sr6_roll_popup_value_1_select_matrix_access: "",
    sr6_roll_popup_value_2_select_matrix_access: "",
    sr6_roll_popup_value_3_select_matrix_access: "",
  };
}

function resetEditModesOnOpen() {
  setAttrsSilent(getEditModeResetPayload());
}
// END MODULE: workers/ui/defaults
