// BEGIN MODULE: workers/rolls/definitions/combat.js
// Roll-Definitionen fuer Kampf: Kernwerte, Waffenangriffe, Verteidigung, Schadenswiderstand und Kampfvergleichswerte.
function createCombatCoreAttackValueSourceByRange(prefix) {
  return {
    "S. Nah": `${prefix}_sehr_nah`,
    "Nah": `${prefix}_nah`,
    "Mittel": `${prefix}_mittel`,
    "Weit": `${prefix}_weit`,
    "S. Weit": `${prefix}_sehr_weit`,
  };
}

const SR6_ROLL_DEFINITIONS_COMBAT = [
{
    id: "combat_ranged_core_attack",
    probeModel: "combat_attack_probe",
    matchField: "Wert",
    matchPoolPrefix: "sr6_combat_fernkampfangriff",
    titleMode: "field-short",
    titleField: "Fertigkeit",
    primaryFields: ["Waffe", "Wert"],
    extraFields: ["Fertigkeit", "Waffentyp", "Schadenswert", "Munition", "Modus", "Reichweite"],
    templateVariant: "weapon",
    contextFields: [
      { label: "Waffe", attr: "sr6_combat_primaere_fernkampfwaffe" },
      { label: "Fertigkeit", attr: "sr6_combat_fernkampf_fertigkeit" },
      { label: "Waffentyp", attr: "sr6_combat_fernkampf_waffentyp" },
      { label: "Munition", attr: "sr6_combat_munition" },
      { label: "Modus", attr: "sr6_combat_fernkampf_modus" },
      { label: "Schadenswert", attr: "sr6_combat_fernkampf_schaden" },
    ],
    fixedTitle: "Fernkampfangriff",
    popupFields: SR6_COMBAT_TAB_POPUP_FIELDS,
    popupDerivedResults: [
      {
        kind: "attack_value",
        label: "Angriffswert",
        sourceByRange: createCombatCoreAttackValueSourceByRange("sr6_combat_fernkampf"),
      },
      { kind: "damage", label: "Schaden", sourceAttr: "sr6_combat_fernkampf_schaden" },
    ],
    titleFallback: "Kampf",
  },
{
    id: "combat_melee_core_attack",
    probeModel: "combat_attack_probe",
    matchField: "Wert",
    matchPoolPrefix: "sr6_combat_nahkampfangriff",
    titleMode: "field-short",
    titleField: "Fertigkeit",
    primaryFields: ["Waffe", "Wert"],
    extraFields: ["Fertigkeit", "Attribut", "Waffentyp", "Schadenswert", "Schadenstyp", "Reichweite"],
    templateVariant: "weapon",
    contextFields: [
      { label: "Waffe", attr: "sr6_combat_primaere_nahkampfwaffe" },
      { label: "Fertigkeit", attr: "sr6_combat_nahkampf_fertigkeit" },
      { label: "Attribut", attr: "sr6_combat_nahkampf_attribut" },
      { label: "Waffentyp", attr: "sr6_combat_nahkampf_waffentyp" },
      { label: "Geschicklichkeit-Wert", attr: "sr6_attr_geschicklichkeit_gesamtwert" },
      { label: "Stärke-Wert", attr: "sr6_attr_staerke_gesamtwert" },
      { label: "Reaktion-Wert", attr: "sr6_attr_reaktion_gesamtwert" },
      { label: "Schadenswert", attr: "sr6_combat_nahkampf_schaden" },
      { label: "Schadenstyp", attr: "sr6_combat_nahkampf_schadentyp" },
    ],
    fixedTitle: "Nahkampfangriff",
    popupFields: createCombatMeleePopupFields("sr6_combat_nahkampf_attribut"),
    popupPoolAttributeOverride: "melee_attribute",
    internalFields: ["Geschicklichkeit-Wert", "Stärke-Wert"],
    popupDerivedResults: [
      {
        kind: "attack_value",
        label: "Angriffswert",
        sourceByRange: createCombatCoreAttackValueSourceByRange("sr6_combat_nahkampf"),
      },
      { kind: "damage", label: "Schaden", sourceAttr: "sr6_combat_nahkampf_schaden" },
    ],
    titleFallback: "Kampf",
  },
{
    id: "physical_defense",
    ...createDefenseProbeDefinition({
      matchPoolPrefix: "sr6_verteidigung_physisch_",
      primaryContextLabel: "Verteidigung (Physisch)",
      comparisonContextLabel: "Verteidigungswert",
      comparisonContextSourceAttr: "sr6_combat_verteidigungswert_gesamtwert",
      titleFallback: "Verteidigung",
    }),
  },
{
    id: "physical_damage_resistance",
    ...createDefenseProbeDefinition({
      matchPoolPrefix: "sr6_schadenswiderstand_physisch_",
      primaryContextLabel: "Schadenswiderstand (Physisch)",
      comparisonContextLabel: "Verteidigungswert",
      comparisonContextSourceAttr: "sr6_combat_verteidigungswert_gesamtwert",
      titleFallback: "Schadenswiderstand",
    }),
  },
{
    id: "general_defense",
    ...createDefenseProbeDefinition({
      matchPoolPrefix: "sr6_verteidigung_",
      primaryContextLabel: "Verteidigung",
      comparisonContextLabel: "Verteidigungswert",
      comparisonContextSourceAttr: "sr6_combat_verteidigungswert_gesamtwert",
      titleFallback: "Verteidigung",
    }),
  },
{
    id: "general_damage_resistance",
    ...createDefenseProbeDefinition({
      matchPoolPrefix: "sr6_schadenswiderstand_",
      primaryContextLabel: "Schadenswiderstand",
      comparisonContextLabel: "Verteidigungswert",
      comparisonContextSourceAttr: "sr6_combat_verteidigungswert_gesamtwert",
      titleFallback: "Schadenswiderstand",
    }),
  },
{
    id: "combat_ranged_weapon",
    probeModel: "combat_attack_probe",
    matchField: "Waffe",
    matchPoolPrefix: "sr6_combat_fernkampf_",
    titleMode: "pool-prefix",
    primaryFields: ["Waffe"],
    extraFields: ["Waffentyp", "Schadenswert", "Munition", "Reichweite", "Modus"],
    templateVariant: "weapon",
    contextFields: [
      { label: "Fertigkeit", attr: "sr6_combat_fernkampf_fertigkeit" },
    ],
    fixedTitle: "Fernkampfangriff",
    popupFields: SR6_COMBAT_TAB_POPUP_FIELDS,
    popupDerivedResults: [
      {
        kind: "attack_value",
        label: "Angriffswert",
        sourceByRange: createAttackValueSourceByRange("sr6_combat_fernkampf"),
      },
      { kind: "damage", label: "Schaden", sourceAttr: "sr6_combat_fernkampf_schaden" },
    ],
    titleFallback: "Kampf",
  },
{
    id: "combat_melee_weapon",
    probeModel: "combat_attack_probe",
    matchField: "Waffe",
    matchPoolPrefix: "sr6_combat_nahkampf_",
    titleMode: "pool-prefix",
    primaryFields: ["Waffe"],
    extraFields: ["Fertigkeit", "Attribut", "Waffentyp", "Schadenswert", "Schadenstyp", "Reichweite"],
    templateVariant: "weapon",
    contextFields: [
      { label: "Fertigkeit", attr: "sr6_combat_nahkampf_fertigkeit" },
      { label: "Attribut", attr: "sr6_combat_nahkampf_attribut" },
      { label: "Waffentyp", attr: "sr6_combat_nahkampf_waffentyp" },
      { label: "Geschicklichkeit-Wert", attr: "sr6_attr_geschicklichkeit_gesamtwert" },
      { label: "Stärke-Wert", attr: "sr6_attr_staerke_gesamtwert" },
      { label: "Reaktion-Wert", attr: "sr6_attr_reaktion_gesamtwert" },
      { label: "Schadenswert", attr: "sr6_combat_nahkampf_schaden" },
      { label: "Schadenstyp", attr: "sr6_combat_nahkampf_schadentyp" },
    ],
    fixedTitle: "Nahkampfangriff",
    popupFields: createCombatMeleePopupFields("sr6_combat_nahkampf_attribut"),
    popupPoolAttributeOverride: "melee_attribute",
    internalFields: ["Geschicklichkeit-Wert", "Stärke-Wert"],
    popupDerivedResults: [
      {
        kind: "attack_value",
        label: "Angriffswert",
        sourceByRange: createAttackValueSourceByRange("sr6_combat_nahkampf"),
      },
      { kind: "damage", label: "Schaden", sourceAttr: "sr6_combat_nahkampf_schaden" },
    ],
    titleFallback: "Kampf",
  },
{
    id: "ranged_weapon",
    probeModel: "combat_attack_probe",
    matchField: "Waffe",
    matchPoolPrefix: "sr6_fernkampf_",
    titleMode: "field-short",
    titleField: "Fertigkeit",
    primaryFields: ["Waffe"],
    extraFields: ["Fertigkeit", "Schadenswert", "Munition", "Modus", "Reichweite"],
    templateVariant: "weapon",
    fixedTitle: "Fernkampfangriff",
    popupFields: SR6_COMBAT_TAB_POPUP_FIELDS,
    popupDerivedResults: [
      {
        kind: "attack_value",
        label: "Angriffswert",
        sourceByRange: createAttackValueSourceByRange("sr6_fernkampf"),
      },
      { kind: "damage", label: "Schaden", sourceAttr: "sr6_fernkampf_schaden" },
    ],
    titleFallback: "Fernkampfwaffen",
  },
{
    id: "melee_weapon",
    probeModel: "combat_attack_probe",
    matchField: "Waffe",
    matchPoolPrefix: "sr6_nahkampf_",
    titleMode: "field-short",
    titleField: "Fertigkeit",
    primaryFields: ["Waffe"],
    extraFields: ["Fertigkeit", "Attribut", "Waffentyp", "Schadenswert", "Schadenstyp", "Reichweite"],
    templateVariant: "weapon",
    contextFields: [
      { label: "Fertigkeit", attr: "sr6_nahkampf_fertigkeit" },
      { label: "Attribut", attr: "sr6_nahkampf_attribut" },
      { label: "Waffentyp", attr: "sr6_nahkampf_waffentyp" },
      { label: "Geschicklichkeit-Wert", attr: "sr6_attr_geschicklichkeit_gesamtwert" },
      { label: "Stärke-Wert", attr: "sr6_attr_staerke_gesamtwert" },
      { label: "Reaktion-Wert", attr: "sr6_attr_reaktion_gesamtwert" },
      { label: "Schadenswert", attr: "sr6_nahkampf_schaden" },
      { label: "Schadenstyp", attr: "sr6_nahkampf_schadentyp" },
    ],
    fixedTitle: "Nahkampfangriff",
    popupFields: createCombatMeleePopupFields("sr6_nahkampf_attribut"),
    popupPoolAttributeOverride: "melee_attribute",
    internalFields: ["Geschicklichkeit-Wert", "Stärke-Wert"],
    popupDerivedResults: [
      {
        kind: "attack_value",
        label: "Angriffswert",
        sourceByRange: createAttackValueSourceByRange("sr6_nahkampf"),
      },
      { kind: "damage", label: "Schaden", sourceAttr: "sr6_nahkampf_schaden" },
    ],
    titleFallback: "Nahkampfwaffen",
  },
{
    id: "weapon",
    // Legacy safety net for weapon-shaped rolls that are not yet mapped to an explicit domain model.
    matchField: "Waffe",
    titleMode: "pool-prefix",
    primaryFields: ["Waffe"],
    extraFields: ["Waffentyp", "Schadenswert", "Munition", "Reichweite", "Modus"],
    popupFields: [
      SR6_DEFAULT_POPUP_FIELDS[0],
      {
        id: "visibility",
        slot: 2,
        label: "Sichtverhältnisse",
        type: "select",
        optionSet: "visibility",
        affects: "pool",
        includeInTemplate: true,
        defaultValue: "clear",
      },
      {
        id: "movement",
        slot: 3,
        label: "Bewegung",
        type: "select",
        optionSet: "movement",
        affects: "pool",
        includeInTemplate: true,
        defaultValue: "steady",
      },
    ],
    titleFallback: "Kampf",
  },
];
// END MODULE: workers/rolls/definitions/combat.js
